baseURL = "https://www.sethitow.com/"
languageCode = "en-us"
title = "Seth Itow"
theme = "hermit-v2"
footerHideThemeName = true

[markup.goldmark.renderer]
  unsafe= true

[params]
  footerHideThemeName = true

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  shareSocial = true

  [params.author]
    name = "Seth Itow"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/sethitow"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sethitow/"

  [[params.socialLinks]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/1927860/seth"

  [[params.socialLinks]]
    name = "youtube"
    url = "https://www.youtube.com/user/Thedingwing"

  [[params.socialLinks]]
    name = "resume"
    url = "/resume"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Photography"
    url = "photo/"
    weight = 15

  # [[menu.main]]
  #   name = "Tech Blog"
  #   url = "posts/tech/"
  #   weight = 10

  # [[menu.main]]
  #   name = "Food Blog"
  #   url = "posts/food/"
  #   weight = 20

  [[menu.main]]
    name = "About / Contact"
    url = "about-contact/"
    weight = 30